"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { ArrowDown, ArrowRight, Bell, BriefcaseBusiness, CalendarDays, Check, ChevronDown, CircleHelp, Clock3, Command, LayoutGrid, List, MoreHorizontal, Plus, Search, Settings2, Sparkles, TrendingUp, X } from "lucide-react";

type Stage = "Applied" | "Interview" | "Offer" | "Rejected";
type Job = { id: string; company: string; role: string; stage: Stage; location: string; date: string; color: string; initials: string; next?: string };
const starter: Job[] = [
  { id: "1", company: "Linear", role: "Senior Product Designer", stage: "Interview", location: "Remote · US", date: "Oct 01, 2026", color: "#5e6ad2", initials: "L", next: "Portfolio review · Oct 04" },
  { id: "2", company: "Vercel", role: "Design Engineer", stage: "Applied", location: "Remote · US", date: "Sep 29, 2026", color: "#171717", initials: "V", next: "Follow up in 3 days" },
  { id: "3", company: "Figma", role: "Product Designer, AI", stage: "Interview", location: "New York, NY", date: "Sep 26, 2026", color: "#f24e1e", initials: "F", next: "Hiring manager · Oct 06" },
  { id: "4", company: "Notion", role: "Staff Product Designer", stage: "Offer", location: "San Francisco, CA", date: "Sep 22, 2026", color: "#191919", initials: "N", next: "Decision due Oct 08" },
  { id: "5", company: "Stripe", role: "Design Systems Lead", stage: "Applied", location: "Remote · US", date: "Sep 18, 2026", color: "#635bff", initials: "S", next: "Follow up in 1 day" },
  { id: "6", company: "Arc", role: "Product Designer", stage: "Rejected", location: "Remote · US", date: "Sep 14, 2026", color: "#6b64f5", initials: "A" },
];
const stages: Stage[] = ["Applied", "Interview", "Offer", "Rejected"];
const blank = { company: "", role: "", stage: "Applied" as Stage, location: "" };

export default function Home() {
  const [jobs, setJobs] = useState<Job[]>(starter);
  const [query, setQuery] = useState("");
  const [stage, setStage] = useState("All applications");
  const [modal, setModal] = useState(false);
  const [draft, setDraft] = useState(blank);
  const [view, setView] = useState<"list" | "board">("list");
  const [ready, setReady] = useState(false);
  useEffect(() => { try { const saved = localStorage.getItem("northstar-jobs"); if (saved) setJobs(JSON.parse(saved)); } catch {} setReady(true); }, []);
  useEffect(() => { if (ready) localStorage.setItem("northstar-jobs", JSON.stringify(jobs)); }, [jobs, ready]);
  const visible = useMemo(() => jobs.filter(j => (stage === "All applications" || j.stage === stage) && `${j.company} ${j.role} ${j.location}`.toLowerCase().includes(query.toLowerCase())), [jobs, query, stage]);
  const addJob = (e: FormEvent) => { e.preventDefault(); if (!draft.company.trim() || !draft.role.trim()) return; const initials = draft.company.slice(0, 1).toUpperCase(); setJobs([{ ...draft, id: crypto.randomUUID(), date: new Intl.DateTimeFormat("en-US", { month: "short", day: "2-digit", year: "numeric" }).format(new Date()), color: "#2d6a58", initials }, ...jobs]); setDraft(blank); setModal(false); };

  return <main className="shell">
    <aside className="sidebar">
      <a className="brand" href="#"><span className="brand-mark"><Sparkles size={16} strokeWidth={2.2}/></span><span>northstar</span></a>
      <button className="workspace"><span className="workspace-icon">SJ</span><span className="workspace-name"><b>Personal workspace</b><small>Free plan</small></span><ChevronDown size={15}/></button>
      <div className="nav-label">WORKSPACE</div>
      <nav><a className="nav-item active" href="#"><LayoutGrid size={17}/>Overview <span className="nav-count">6</span></a><a className="nav-item" href="#applications"><BriefcaseBusiness size={17}/>Applications</a><a className="nav-item" href="#calendar"><CalendarDays size={17}/>Interview calendar <span className="nav-dot"/></a></nav>
      <div className="nav-label list-label">YOUR LISTS <button aria-label="Add list"><Plus size={14}/></button></div>
      <nav><a className="nav-item muted" href="#"><span className="list-color mint"/>Design roles</a><a className="nav-item muted" href="#"><span className="list-color lilac"/>Dream companies</a><a className="nav-item muted" href="#"><Plus size={15}/>Create a list</a></nav>
      <div className="sidebar-bottom"><div className="tip-card"><div className="tip-icon"><Sparkles size={15}/></div><b>A little progress<br/>adds up.</b><p>You’re building momentum. Keep showing up for your future self.</p><span>YOUR WEEKLY NOTE · 01</span></div><a className="nav-item muted" href="#"><CircleHelp size={16}/>Help & feedback</a><a className="nav-item muted" href="#"><Settings2 size={16}/>Settings</a><div className="profile"><div className="avatar">SJ</div><div><b>Saurabh Jaju</b><small>Personal account</small></div><MoreHorizontal size={17}/></div></div>
    </aside>
    <section className="main-area">
      <header className="topbar"><div className="breadcrumbs">Workspace <span>/</span> <b>Overview</b></div><div className="top-actions"><button className="search-button" onClick={() => document.getElementById("search")?.focus()}><Search size={15}/><span>Search anything...</span><kbd><Command size={10}/> K</kbd></button><button className="icon-button" aria-label="Notifications"><Bell size={17}/><i/></button><div className="avatar top-avatar">SJ</div></div></header>
      <div className="content">
        <div className="welcome-row"><div><div className="eyebrow"><span className="status-live"/> TUESDAY, OCTOBER 1, 2026</div><h1>Your next chapter<br/><span>starts here.</span></h1><p className="intro">A clear view of your search, one step at a time.</p></div><div className="welcome-art"><div className="art-sun"/><div className="art-hill hill-back"/><div className="art-hill hill-front"/><div className="art-star">✳</div><div className="art-label">KEEP GOING <span>↗</span></div></div></div>
        <div className="metrics"><article className="metric-card"><div className="metric-top"><span>IN THE PIPELINE</span><span className="metric-icon green"><BriefcaseBusiness size={15}/></span></div><strong>{jobs.length.toString().padStart(2,"0")}</strong><div className="metric-foot"><span className="trend"><TrendingUp size={13}/> +2 this week</span><span>across your search</span></div></article><article className="metric-card"><div className="metric-top"><span>CONVERSATIONS</span><span className="metric-icon yellow"><Clock3 size={15}/></span></div><strong>{jobs.filter(j => j.stage === "Interview").length.toString().padStart(2,"0")}</strong><div className="metric-foot"><span>interviews in motion</span></div></article><article className="metric-card"><div className="metric-top"><span>RESPONSE RATE</span><span className="metric-icon purple"><TrendingUp size={15}/></span></div><strong>{jobs.length ? `${Math.round(jobs.filter(j=>j.stage!=="Applied").length/jobs.length*100)}%` : "0%"}</strong><div className="metric-foot"><span>applications with a response</span></div></article><article className="metric-card next-step"><div className="metric-top"><span>NEXT UP</span><span className="metric-icon blue"><CalendarDays size={15}/></span></div><strong className="next-title">{jobs.find(j=>j.stage==="Interview")?.company ?? "Take a breath"}</strong><div className="metric-foot"><span>{jobs.find(j=>j.stage==="Interview")?.next ?? "Your search is in your hands"}</span></div></article></div>
        <div className="section-heading"><div><div className="heading-overline">YOUR SEARCH, AT A GLANCE</div><h2>Applications <span className="total-pill">{jobs.length}</span></h2></div><button className="primary-button" onClick={() => setModal(true)}><Plus size={16}/> Add application</button></div>
        <div className="toolbar"><div className="tabs">{["All applications", ...stages].map(t=><button key={t} className={`tab ${stage===t?"selected":""}`} onClick={()=>setStage(t)}>{t}<span>{t==="All applications"?jobs.length:jobs.filter(j=>j.stage===t).length}</span></button>)}</div><div className="table-actions"><label className="search-field"><Search size={14}/><input id="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search roles..."/></label><button className={`view-toggle ${view==="list"?"on":""}`} aria-label="List view" onClick={()=>setView("list")}><List size={16}/></button><button className={`view-toggle ${view==="board"?"on":""}`} aria-label="Board view" onClick={()=>setView("board")}><LayoutGrid size={15}/></button><button className="sort-button">Newest first <ArrowDown size={13}/></button></div></div>
        {view==="list"?<div className="table-wrap"><table><thead><tr><th>COMPANY & ROLE</th><th>STATUS</th><th>LOCATION</th><th>APPLIED</th><th>NEXT STEP</th><th/></tr></thead><tbody>{visible.map(job=><tr key={job.id}><td><div className="company-cell"><span className="company-logo" style={{background:job.color}}>{job.initials}</span><span><b>{job.company}</b><small>{job.role}</small></span></div></td><td><span className={`badge ${job.stage.toLowerCase()}`}><i/>{job.stage}</span></td><td className="muted-cell">{job.location}</td><td className="muted-cell">{job.date}</td><td className="next-cell">{job.next ?? <span className="no-step">—</span>}</td><td><button className="row-menu" aria-label={`Remove ${job.company}`} onClick={()=>setJobs(jobs.filter(j=>j.id!==job.id))}><MoreHorizontal size={17}/></button></td></tr>)}{visible.length===0&&<tr><td colSpan={6} className="empty">No applications match. Try a different search or add a role.</td></tr>}</tbody></table></div>:<div className="board">{stages.map(s=><section className="board-column" key={s}><h3>{s}<span>{visible.filter(j=>j.stage===s).length}</span></h3>{visible.filter(j=>j.stage===s).map(job=><article className="board-card" key={job.id}><div className="company-cell"><span className="company-logo" style={{background:job.color}}>{job.initials}</span><span><b>{job.company}</b><small>{job.role}</small></span></div><p>{job.location}</p><footer><span>{job.date}</span><select aria-label={`Change ${job.company} stage`} value={job.stage} onChange={e=>setJobs(jobs.map(j=>j.id===job.id?{...j,stage:e.target.value as Stage}:j))}>{stages.map(x=><option key={x}>{x}</option>)}</select></footer></article>)}</section>)}</div>}
        <div className="bottom-note"><div className="note-icon"><Check size={14}/></div><span><b>You’re right where you need to be.</b> Every application is a step forward.</span><a href="#">View your search insights <ArrowRight size={14}/></a></div>
        <footer className="page-footer"><span>MADE FOR THE IN-BETWEEN</span><span>YOUR DATA STAYS YOURS · <a href="#">PRIVACY</a></span></footer>
      </div>
    </section>
    {modal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(false)}}><form className="modal" onSubmit={addJob}><button type="button" className="modal-close" onClick={()=>setModal(false)} aria-label="Close"><X size={18}/></button><div className="modal-icon"><Plus size={18}/></div><div className="heading-overline">A NEW BEGINNING</div><h2>Add an application</h2><p>Capture the opportunity. You can fill in the details as you go.</p><label>Company<input autoFocus value={draft.company} onChange={e=>setDraft({...draft,company:e.target.value})} placeholder="e.g. Acme Studio" required/></label><label>Role<input value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})} placeholder="e.g. Product Designer" required/></label><label>Location<input value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})} placeholder="e.g. Remote"/></label><label>Status<select value={draft.stage} onChange={e=>setDraft({...draft,stage:e.target.value as Stage})}>{stages.map(s=><option key={s}>{s}</option>)}</select></label><div className="modal-actions"><button type="button" className="cancel-button" onClick={()=>setModal(false)}>Cancel</button><button className="primary-button" type="submit"><Plus size={15}/> Add to my search</button></div></form></div>}
  </main>;
}

